name:         Spreadsheet-WriteExcel
version:      2.14.2
version_from: lib/Spreadsheet/WriteExcel.pm
installdirs:  site
requires:
    File::Temp:                    0
    Parse::RecDescent:             0

distribution_type: module
generated_by: hand
