name:               Spreadsheet-WriteExcel
abstract:           Write to a cross platform Excel binary file
version:            2.22
version_from:       lib/Spreadsheet/WriteExcel.pm
installdirs:        site
requires:
    File::Temp:                    0
    OLE::Storage_Lite:             0.14
    Parse::RecDescent:             0

distribution_type:  module
license:            perl
generated_by:       hand
resources:
    CPANForum: http://groups.google.com/group/spreadsheet-writeexcel
    GoogleGroup: http://groups.google.com/group/spreadsheet-writeexcel
