name:               Spreadsheet-WriteExcel
version:            2.10
version_from:       lib/Spreadsheet/WriteExcel.pm
installdirs:        site
requires:
    File::Temp:                    0
    Parse::RecDescent:             0

distribution_type:  module
generated_by:       hand
